name: Ansible Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.3]
        ansible-version: [2.9.10]
        lint-version: [4.1.0]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Ansible ${{ matrix.ansible-version }}
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint==${{ matrix.lint-version }} ansible==${{ matrix.ansible-version }}
    - name: Lint playbook
      run: |
        git clone https://github.com/tosin2013/qubinode-installer.git
        cd qubinode-installer
        git checkout python-build
        ansible-galaxy install git+https://github.com/Qubinode/qubinode_kvmhost_setup.git,dev --force
        ansible-lint -x 206,204 project/setup_kvmhost.yml
    - name: Ansible Check 
      run: |
        mkdir -p /home/runner/roles:
        cd $HOME 
        ln -s   /home/runner/qubinode-installer/project/roles/qubinode_kvmhost_setup /home/runner/roles:
        cat >test.yml<<EOF
        - hosts: localhost
          become: yes
          vars:
            kvm_host_ip: 127.0.0.1
            kvm_host_interface: eth0
            kvm_host_gw: 127.0.0.1
            kvm_host_macaddr: example
            kvm_host_netmask: 255.255.255.0
            kvm_host_mask_prefix: 24
            ssh_username: admin
            vm_libvirt_net: qubinet
            cicd_test: true
          roles:
            - qubinode_kvmhost_setup
        EOF
        ansible-playbook  test.yml --check -v

